#%RAML 1.0 NamedExample
value:
 id: 01
 name: Eagle Airlines
 email: customer@eagle-airlines.com
 billTo-street: 2244 Craftman St
 billTo-city: Santa Barbara
 billTo-state: Ca
 billTo-zip: 94673-9600
 billTo-country: USA
 lastMmodified: 2017-03-28 22:01:36 s