#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/875b1dce-f1c0-4ecd-8a11-2b70bf81111a # 
title: Customer Presto System API
version: 1.0

types:
  customer: !include dataTypes/customer.raml


/presto/customers:
  description: Customer collection resource
  get:
    description: Use this method to get all customers stored in Presto DB.
    displayName: Get customers stored in Presto
    responses: 
      200:
        body: 
          application/json:
            example: !include examples/customers.raml
  
  /presto/{customer_id}:
    description: Get a customer from Presto DB
    get:
      description: Retrieve information of customer using the customer id.
      displayName: Get information from a customer
      responses: 
        200:
          body: 
            application/json:
              example: !include examples/customer.raml